### PR TITLE
feat(tree) added tag for untranslated items #197

### PR DESCRIPTION
**Pull request by clementdevos**
Hey there, 

I finally took time to implement this in the app, hope it will meet expectations.

### CODE REVIEW

**Comment by gilmarsquinelato** [comment]
Hey @clementdevos, I really thank you for the PR, but I'm developing the v3, and that version is completely different from v2.

The new UI is built with Vue, and the Tree algorithm is completely different.
Hopefully, I'll release it soon.

**Comment by gilmarsquinelato** [comment]
Another thing is that we'll have filters to show only untranslated keys and duplicated values.
This I think that will cover your implementation.

**Comment by clementdevos** [comment]
Oh allright, looks like i'm late to the party. 

Having testing both, i'd be curious why you'd switch from vue to react aha. 

Good luck with the v3 ;)

**Comment by gilmarsquinelato** [comment]
Ty 😁
I changed to Vue because the productivity and performance.
Some benchmarks shown the performance difference.
And since this app renders a lot of items, almost every ms counts.

**Pull request closed without merging**
