### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by reallinfo**
logo updated.

### CODE REVIEW

**Comment by reallinfo** [comment]
Of course, what's wrong? Could you please tell me exactly what to do?

**Comment by gilmarsquinelato** [comment]
The checker is reporting that *logo/horizontal.png* and *logo/logomark.png* files are conflicting.

You need to backup these files, and update your repository from my branch, because I have a more recent branch. After that, you can place the new files again a commit them.

**Comment by reallinfo** [comment]
The resolve conflicts button appears disabled. actually I don't use github very well and I don't use git for edits.  

image

I tried to get information from that connection, but I couldn't.
https://help.github.com/articles/resolving-a-merge-conflict-on-github/

so I don't want to do anything wrong. I have uploaded all the files to the drive. could you upload the files please?  sorry for the mishap.

https://drive.google.com/open?id=1YjmcWEWbcUcI_54OKwcUhTvwTnfff0vo

**Comment by gilmarsquinelato** [comment]
No problem @reallinfo, I can do that. Thank you again for the great job!

**Comment by reallinfo** [comment]
Thanks for your understanding. You can reach me for all your design needs. ( github or personel request ) I can help you. Here is my mail adress: komiserback@gmail.com

**Comment by gilmarsquinelato** [comment]
I'll close this PR and open a new with your new designs.

**Pull request closed without merging**
