### PR TITLE
add copy item key feature

### PR DESCRIPTION
**Pull request by fang5502**
Hi, this feature makes it easier to develop.

### CODE REVIEW

**Comment by gilmarsquinelato** [comment]
Hi @fang5502, thanks for the PR, but we could discuss the feature before the implementation :)
What is this feature? how it will work? what is the purpose of it?
These question would be better fit before merge it.
And one last thing, have in mind that I'm releasing the v2 of the app, so merge again your branch from develop and be sure it keeps working.

**Comment by gilmarsquinelato** [comment]
Closing due to lack of response

**Comment by fang5502** [comment]
Hi, I am sorry to reply so long.

I use i18n in airbnb/polyglot.js, and I need json key to get the corresponding string , so I added "copy item key" to develop easier.

Also, I would like to know when to use this tool.

Thank you!

**Comment by gilmarsquinelato** [comment]
Hey @fang5502, no problem, I will develop that feature ok? Because the interface was changed to react since your PR.
And this tool can be used in any translation folder, independently of the i18n library is being used.

**Comment by fang5502** [comment]
Ok, I think it would be better to match i18n library.

**Comment by gilmarsquinelato** [comment]
This isn't possible, because of the nature of the tool is to be agnostic, and this makes possible to read different file formats, like JSON, YAML and more in the future.
In the future will be possible to create separated plugins (file format parsers) and just add into the app, like VSCode do today.

Because of this nature, we can't lock the tool to a specific i18n library

**Pull request closed without merging**
